### ISSUE TITLE
Intermittent issue with s3 replication plugin

### ISSUE THREAD

**Issue by sushantbhat** [awslabs/amazon-s3-data-replication-hub-plugin#41] opened 2021-05-25 12:08 UTC
Noticed that sometimes the messages from the SQS queue are not consumed by the JobWorker and stayed waiting for a few days. When a new item was added to s3, event got triggered and the message was added to the queue and no. of messages available got incremented and the waiting job count in the cloudwatch dashboard got incremented as well. However, it stayed in waiting state and never got transferred. Only after terminating the ec2 instance and a new instance got launched it resumed transferring the objects. 
Apart from the s3 trigger, even the hourly job got affected as well due to this and it wasn't able poll the source and destination buckets completely.
This was the error in the log of job finder.
_2021-05-24T12:51:47.982+05:30	2021/05/24 07:21:47 Start running Finder job
2021-05-24T12:51:48.336+05:30	2021/05/24 07:21:48 Get Parameter Value of china_keys from SSM
2021-05-24T12:51:48.782+05:30	2021/05/24 07:21:48 Queue DTHS3Stack-S3TransferQueue-7QIV4XZ7OKM1 has 0 not visible message(s) and 3 visable message(s)
2021-05-24T12:51:48.782+05:30	2021/05/24 07:21:48 Queue might not be empty or Unknown error... Please try again later_

**To Reproduce**
The issue is intermittent, unable to reproduce.

**Please complete the following information about the solution:**
- [ ] Version: v2.0.0
- [ ] Region: [e.g. us-west-2]
- [ ] Was the solution modified from the version published on this repository? No (only the cron job frequency was changed to daily from hourly)
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [ ] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [ ] Were there any errors in the CloudWatch Logs? Yes, logs attached above.

**Comment by YikaiHu** [comment] 2021-05-25 12:35
Hi @sushantbhat , 
Could you check the EC2 JobWorker's log in CloudWatch Log groups when the SQS jobs ignored by the workers? The log groups' name is like '<Your Stack Name>xxxxxxWorkerLogGroupxxxxxxxx'
B, R

**Comment by sushantbhat** [comment] 2021-05-26 04:56
@YikaiHu Seems like 'xxxxxxWorkerLogGroupxxxxxxxx' wasn't logging anything. There are no log streams after May-03 until it was restarted a couple of days back. And even the logs before that are empty now not even the normal logging that says 'No messages, sleep...'.

**Comment by YikaiHu** [comment] 2021-05-27 03:50
@sushantbhat  
For issue 1: "However, it stayed in waiting state and never got transferred."

Have you ever restarted the EC2 Workers before this issue occur?
It seems like the transfer cli in your EC2 Workers shut down for some reason. If this case occur, you have to terminate these  'dead' Workers, and Auto Scaling Groups will launch new Workers to consumption the jobs in SQS.

For issue 2: "This was the error in the log of job finder ....  _Queue might not be empty or Unknown error... Please try again later_"

This is a normal mechanism, and the Finder is designed to check whether SQS is empty before comparing.

**Comment by sushantbhat** [comment] 2021-05-27 07:06
No, I haven't restarted ec2 workers before. Only after this issue happened, ec2 worker was terminated, and like you mentioned it relaunched another instance that started working as expected. 
However, wanted to know what could have caused JobWorker to fail, as we are planning to go production with this solution and anything that can be done to prevent this from occurring in the future. 
And also is there any notification mechanism that can be enabled for such cases where JobWorker fails and messages are stuck in waiting state?

**Comment by YikaiHu** [comment] 2021-06-01 05:59
@sushantbhat 
The most efficient method to find out the root cause of the issue is to check the EC2 system log in the EC2 console (Actions -> Monitor and troubleshoot -> Get system log) and check whether the JobWorker's CLI is running.
The reasons which can cause JobWorker to fail:
1. Customer restart the EC2 Worker instances.
2. Customer edit the EC2 user data may cause the instance cannot download the CLI successfully
In this version, we don't have notification mechanism for Worker failure.

**Closed** 2022-01-05 01:40 UTC
